import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function DashboardCommandCenter() {
    const actions = [
        { title: "Fix missing meta descriptions", desc: "12 pages affected • SEO impact high" },
        { title: "Compress hero images", desc: "2.8MB savings • Performance boost" },
        { title: "Resolve broken links", desc: "5 broken URLs detected" },
    ];
    const services = [
        { name: "Backend API", status: "Online" },
        { name: "Audit Engine", status: "Online" },
        { name: "Pagespeed", status: "Standby" },
    ];
    return (_jsxs("div", { className: "mt-6 grid grid-cols-1 gap-4 xl:grid-cols-3", children: [_jsxs("div", { className: "xl:col-span-2 rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-sm font-semibold text-white/90", children: "Command Center" }), _jsx("span", { className: "text-xs text-white/50", children: "Last 7 days" })] }), _jsxs("div", { className: "mt-4 grid grid-cols-1 gap-3 md:grid-cols-2", children: [_jsxs("div", { className: "rounded-xl border border-white/10 bg-black/20 p-4", children: [_jsx("p", { className: "text-xs text-white/60", children: "Score trend" }), _jsx("div", { className: "mt-2 h-16 rounded-lg border border-white/10 bg-black/20" }), _jsx("p", { className: "mt-2 text-xs text-white/50", children: "Sparkline placeholder (branch later)" })] }), _jsxs("div", { className: "rounded-xl border border-white/10 bg-black/20 p-4", children: [_jsx("p", { className: "text-xs text-white/60", children: "Recent analyses" }), _jsxs("ul", { className: "mt-2 space-y-2 text-xs text-white/70", children: [_jsx("li", { children: "\u2022 Homepage audit completed" }), _jsx("li", { children: "\u2022 Performance scan saved" }), _jsx("li", { children: "\u2022 Keyword audit updated" })] })] })] })] }), _jsxs("div", { className: "rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur", children: [_jsx("h3", { className: "text-sm font-semibold text-white/90", children: "Recommended actions" }), _jsx("div", { className: "mt-3 space-y-3", children: actions.map((a) => (_jsxs("div", { className: "rounded-xl border border-white/10 bg-black/20 p-3", children: [_jsx("p", { className: "text-sm text-white/90", children: a.title }), _jsx("p", { className: "mt-1 text-xs text-white/60", children: a.desc }), _jsx("button", { className: "mt-3 rounded-lg border border-white/10 bg-white/10 px-3 py-1 text-xs text-white/90 hover:bg-white/15", children: "Open" })] }, a.title))) }), _jsx("h3", { className: "mt-6 text-sm font-semibold text-white/90", children: "Services" }), _jsx("div", { className: "mt-3 space-y-2", children: services.map((s) => (_jsxs("div", { className: "flex items-center justify-between rounded-lg border border-white/10 bg-black/20 px-3 py-2", children: [_jsx("span", { className: "text-xs text-white/70", children: s.name }), _jsx("span", { className: "text-xs text-emerald-300", children: s.status })] }, s.name))) })] })] }));
}
